import { Fragment, useEffect, useMemo, useState } from "react";
import Layout from "../shared/Layout";
import ReportFormShell from "../shared/ReportFormShell";
import ReportFormLeft from "../shared/ReportFormLeft";
import ReportFormRight from "../shared/ReportFormRight";

const SLIDERS = [
  { label: "Course At Risk Threshold", stateKey: "courseAtRisk" },
  { label: "Student At Risk Threshold", stateKey: "studentAtRisk" },
];

const API_BASE = "http://localhost:5000";

export default function CategoryPerformanceReport({
  onBack,
  onReportCreated,
  initialConfig,
}) {
  const [reportDbId, setReportDbId] = useState(initialConfig?.id || null);
  const [reportName, setReportName] = useState(
    initialConfig?.config?.reportName || initialConfig?.reportName || "",
  );
  const [startDate, setStartDate] = useState(
    initialConfig?.config?.startDate || initialConfig?.startDate || "",
  );
  const [endDate, setEndDate] = useState(
    initialConfig?.config?.endDate || initialConfig?.endDate || "",
  );

  const [courses, setCourses] = useState([]);
  const [courseId, setCourseId] = useState(
    initialConfig?.config?.courseId || initialConfig?.courseId || "",
  );

  const [assessmentTypes, setAssessmentTypes] = useState(
    initialConfig?.config?.assessmentTypes ||
      initialConfig?.assessmentTypes || {
        Exam: true,
        Quiz: true,
        Assignment: true,
      },
  );
  const [sliderValues, setSliderValues] = useState(
    initialConfig?.config?.sliderValues ||
      initialConfig?.sliderValues || {
        courseAtRisk: 70,
        studentAtRisk: 70,
      },
  );

  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState("");
  const [report, setReport] = useState(null);
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [isEditing, setIsEditing] = useState(!initialConfig);

  // --- DELETE CONFIRMATION STATE ---
  const [isConfirmingDelete, setIsConfirmingDelete] = useState(false);

  const [studentsByAssessment, setStudentsByAssessment] = useState({});
  const [loadingStudentsFor, setLoadingStudentsFor] = useState(null);

  const selectedTypesString = useMemo(() => {
    return Object.entries(assessmentTypes)
      .filter(([, enabled]) => enabled)
      .map(([type]) => type)
      .join(",");
  }, [assessmentTypes]);

  const courseName = useMemo(() => {
    return courses.find((c) => c._id === courseId)?.name || "";
  }, [courses, courseId]);

  useEffect(() => {
    let cancelled = false;
    const loadCourses = async () => {
      try {
        const res = await fetch(`${API_BASE}/api/courses`);
        const json = await res.json();
        if (!cancelled) setCourses(json.data || []);
      } catch {
        /* ignore */
      }
    };
    loadCourses();
    return () => {
      cancelled = true;
    };
  }, []);

  useEffect(() => {
    if (initialConfig && courses.length > 0 && !autoGenerated) {
      setAutoGenerated(true);
      generateReport(true);
    }
  }, [initialConfig, courses, autoGenerated]);

  const generateReport = async (isAutoGenerate = false) => {
    if (!courseId) {
      setError("Please select a course.");
      return;
    }

    const q = new URLSearchParams();
    if (startDate) q.set("startDate", startDate);
    if (endDate) q.set("endDate", endDate);
    if (selectedTypesString) q.set("types", selectedTypesString);
    q.set("thresholdCourse", sliderValues.courseAtRisk);
    q.set("thresholdStudent", sliderValues.studentAtRisk);

    setIsGenerating(true);
    setError("");
    setReport(null);

    try {
      const [summaryRes, assessmentsRes] = await Promise.all([
        fetch(
          `${API_BASE}/api/reports/course?courseId=${courseId}&${q.toString()}`,
        ),
        fetch(
          `${API_BASE}/api/reports/courses/${courseId}/assessments?${q.toString()}`,
        ),
      ]);

      const summaryJson = await summaryRes.json();
      const assessmentsJson = await assessmentsRes.json();

      if (!summaryRes.ok || !assessmentsRes.ok) {
        throw new Error(
          summaryJson?.error?.message ||
            assessmentsJson?.error?.message ||
            "Failed to generate report",
        );
      }

      setReport({
        summary: summaryJson.data,
        assessments: assessmentsJson.data,
        startedAt: startDate,
        endedAt: endDate,
        selectedTypesString,
        thresholds: {
          courseAtRisk: sliderValues.courseAtRisk,
          studentAtRisk: sliderValues.studentAtRisk,
        },
      });

      if (!isAutoGenerate) {
        const payload = {
          name: reportName.trim() || "Course Performance",
          type: "Course Performance",
          courseName,
          config: {
            reportName,
            startDate,
            endDate,
            courseId,
            assessmentTypes,
            sliderValues,
          },
        };

        if (reportDbId) {
          await fetch(`${API_BASE}/api/saved-reports/${reportDbId}`, {
            method: "PUT",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(payload),
          });
        } else {
          const postRes = await fetch(`${API_BASE}/api/saved-reports`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(payload),
          });
          const postJson = await postRes.json();
          if (postJson.success) setReportDbId(postJson.data.id);
        }

        if (typeof onReportCreated === "function") onReportCreated();
      }

      setIsEditing(false);
    } catch (e) {
      setError(e?.message || "Failed to generate report");
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDelete = async () => {
    // Stage 1: Ask for confirmation
    if (!isConfirmingDelete) {
      setIsConfirmingDelete(true);
      return;
    }

    // Stage 2: Proceed with API call
    if (!reportDbId) {
      onBack();
      return;
    }
    try {
      await fetch(`${API_BASE}/api/saved-reports/${reportDbId}`, {
        method: "DELETE",
      });
      if (typeof onReportCreated === "function") onReportCreated();
      onBack();
    } catch (e) {
      setError("Failed to delete report.");
      setIsConfirmingDelete(false);
    }
  };

  const fetchStudentsForAssessment = async (assessmentId) => {
    if (!assessmentId) return;
    setLoadingStudentsFor(assessmentId);
    try {
      const q = new URLSearchParams();
      q.set("thresholdStudent", sliderValues.studentAtRisk);
      if (startDate) q.set("startDate", startDate);

      const res = await fetch(
        `${API_BASE}/api/reports/assessments/${assessmentId}/students?${q.toString()}`,
      );
      const json = await res.json();
      if (!res.ok)
        throw new Error(json?.error?.message || "Failed to fetch students");
      setStudentsByAssessment((prev) => ({
        ...prev,
        [assessmentId]: json.data || [],
      }));
    } catch (e) {
      setStudentsByAssessment((prev) => ({ ...prev, [assessmentId]: [] }));
    } finally {
      setLoadingStudentsFor(null);
    }
  };

  const atRiskAssessmentsCount =
    report?.assessments?.filter((a) => a.status === "At Risk").length || 0;
  const totalAssessmentsCount = report?.assessments?.length || 0;

  const renderReportBody = () => (
    <div className="report-body-container pt-2">
      <div className="mb-4">
        <div
          style={{
            fontSize: 18,
            fontWeight: 400,
            color: "#333",
            marginBottom: 12,
          }}
        >
          Course Performance Report
        </div>

        <div
          style={{
            display: "flex",
            gap: "10px",
            fontSize: "11px",
            fontWeight: "600",
            color: "#555",
            textTransform: "uppercase",
          }}
        >
          <span>
            <strong style={{ color: "#d32f2f" }}>
              At-Risk Course: {report.summary?.atRiskCourseCount ?? 0}
            </strong>{" "}
            | Total Courses: {report.summary?.totalCourses ?? 0}
          </span>
        </div>
        <div style={{ fontSize: "11px", color: "#666", marginTop: "4px" }}>
          Date Range: {report.startedAt || "Any"} - {report.endedAt || "Any"}{" "}
          &nbsp;|&nbsp; At-Risk Course Threshold:{" "}
          {report.thresholds.courseAtRisk}% &nbsp;|&nbsp; At-Risk Student
          Threshold: {report.thresholds.studentAtRisk}%
        </div>
      </div>

      <div
        className="report-card"
        style={{
          background: "white",
          padding: "20px",
          border: "1px solid #ddd",
          boxShadow: "0 1px 3px rgba(0,0,0,0.05)",
        }}
      >
        <div className="d-flex align-items-center mb-3">
          <span style={{ fontSize: "18px", color: "#333" }}>
            {courseName || "Unknown Course"}
          </span>
        </div>

        <div style={{ fontSize: "12px", color: "#666", marginBottom: "20px" }}>
          At-Risk Assessments: {atRiskAssessmentsCount} &nbsp;|&nbsp; At-Risk
          Students: {report.summary?.atRiskStudents ?? 0}/
          {report.summary?.totalStudents ?? 0} &nbsp;|&nbsp; Total Assessments:{" "}
          {totalAssessmentsCount} &nbsp;|&nbsp; Total Quizzes:{" "}
          {report.assessments?.filter((a) => a.type === "Quiz").length || 0}
        </div>

        <div
          className="d-flex flex-column flex-sm-row justify-content-between align-items-sm-end mb-2 gap-2"
          style={{ borderTop: "1px solid #eee", paddingTop: "15px" }}
        >
          <div
            style={{
              fontSize: 13,
              fontWeight: 700,
              color: "#333",
              textTransform: "uppercase",
            }}
          >
            Assessments
          </div>
          <div
            className="d-flex flex-wrap gap-2 gap-sm-3 align-items-center"
            style={{
              fontSize: 11,
              color: "#555",
            }}
          >
            <span>
              <svg
                width="10"
                height="10"
                style={{ fill: "#d32f2f", transform: "translateY(2px)" }}
              >
                <path d="M0,0 L10,0 L5,8 Z" />
              </svg>{" "}
              At-Risk
            </span>
            <span>
              <svg
                width="10"
                height="10"
                style={{ fill: "#388e3c", transform: "translateY(1px)" }}
              >
                <path d="M5,0 L10,8 L0,8 Z" />
              </svg>{" "}
              Doing Well
            </span>
          </div>
        </div>

        <div className="table-responsive" style={{ borderRadius: '3px' }}>
          <table
            className="table"
            style={{ border: "1px solid #ddd", borderBottom: "none", minWidth: "850px" }}
          >
          <thead>
            <tr
              style={{
                background: "#516275",
                color: "#fff",
                fontSize: "10px",
                letterSpacing: "0.5px",
              }}
            >
              <th
                style={{
                  padding: "12px 16px",
                  fontWeight: "600",
                  border: "none",
                }}
              >
                NAME ▾
              </th>
              <th
                style={{
                  padding: "12px 16px",
                  fontWeight: "600",
                  border: "none",
                }}
              >
                TYPE ▾
              </th>
              <th
                style={{
                  padding: "12px 16px",
                  fontWeight: "600",
                  border: "none",
                }}
              >
                SCHEDULED ON ▾
              </th>
              <th
                style={{
                  padding: "12px 16px",
                  fontWeight: "600",
                  border: "none",
                }}
              >
                AVG SCORE ▾
              </th>
              <th
                style={{
                  padding: "12px 16px",
                  fontWeight: "600",
                  border: "none",
                }}
              >
                STATUS ▾
              </th>
              <th
                style={{
                  padding: "12px 16px",
                  fontWeight: "600",
                  border: "none",
                  width: "120px",
                }}
              ></th>
            </tr>
          </thead>
          <tbody>
            {report.assessments?.length ? (
              report.assessments.map((a) => (
                <Fragment key={a._id}>
                  <tr
                    style={{
                      borderBottom: "1px solid #ddd",
                      background: "white",
                    }}
                  >
                    <td
                      style={{ verticalAlign: "middle", padding: "12px 16px" }}
                    >
                      <div
                        style={{
                          fontSize: "13px",
                          color: "#333",
                          marginBottom: "4px",
                        }}
                      >
                        {a.name}
                      </div>
                      <div
                        style={{
                          position: "relative",
                          width: "100%",
                          height: "8px",
                          background: "#e0e0e0",
                          borderRadius: "1px",
                          marginTop: "15px",
                        }}
                      >
                        <div
                          style={{
                            position: "absolute",
                            left: `${Math.min(100, Math.max(0, a.avgScore))}%`,
                            top: "-6px",
                            transform: "translateX(-50%)",
                          }}
                        >
                          <svg
                            width="12"
                            height="12"
                            viewBox="0 0 10 10"
                            style={{
                              fill: "none",
                              stroke: "#cfa625",
                              strokeWidth: "2",
                            }}
                          >
                            <path d="M5 1L9 5L5 9L1 5Z" />
                          </svg>
                        </div>
                      </div>
                      <div
                        style={{
                          display: "flex",
                          justifyContent: "space-between",
                          fontSize: "10px",
                          color: "#999",
                          marginTop: "2px",
                        }}
                      >
                        <span>0</span>
                        <span>50</span>
                        <span>100</span>
                      </div>
                    </td>
                    <td
                      style={{
                        verticalAlign: "middle",
                        fontSize: "13px",
                        color: "#333",
                        padding: "12px 16px",
                      }}
                    >
                      {a.type.toUpperCase()}
                    </td>
                    <td
                      style={{
                        verticalAlign: "middle",
                        fontSize: "13px",
                        color: "#333",
                        padding: "12px 16px",
                      }}
                    >
                      {a.date ? new Date(a.date).toLocaleDateString() : "-"}
                    </td>
                    <td
                      style={{
                        verticalAlign: "middle",
                        fontSize: "13px",
                        color: "#333",
                        padding: "12px 16px",
                      }}
                    >
                      {Number(a.avgScore ?? 0).toFixed(2)}%
                    </td>
                    <td
                      style={{ verticalAlign: "middle", padding: "12px 16px" }}
                    >
                      {a.status === "At Risk" ? (
                        <svg width="12" height="12" style={{ fill: "#d32f2f" }}>
                          <path d="M0,0 L12,0 L6,10 Z" />
                        </svg>
                      ) : (
                        <svg width="12" height="12" style={{ fill: "#388e3c" }}>
                          <path d="M6,0 L12,10 L0,10 Z" />
                        </svg>
                      )}
                    </td>
                    <td
                      style={{
                        verticalAlign: "middle",
                        padding: "12px 16px",
                        textAlign: "right",
                      }}
                    >
                      <a
                        href="#"
                        style={{
                          color: "#1a73c1",
                          fontSize: "13px",
                          textDecoration: "none",
                        }}
                        onClick={(e) => {
                          e.preventDefault();
                          const current = studentsByAssessment[a._id];
                          if (current) {
                            setStudentsByAssessment((prev) => {
                              const n = { ...prev };
                              delete n[a._id];
                              return n;
                            });
                          } else fetchStudentsForAssessment(a._id);
                        }}
                      >
                        {loadingStudentsFor === a._id
                          ? "Loading..."
                          : "Student List"}
                      </a>
                    </td>
                  </tr>

                  {studentsByAssessment[a._id] ? (
                    <tr>
                      <td colSpan={6} style={{ padding: "0" }}>
                        <div
                          style={{
                            padding: "0 0 0 40px",
                            background: "#f5f5f5",
                          }}
                        >
                          <div
                            style={{
                              display: "flex",
                              alignItems: "center",
                              padding: "15px 15px 10px",
                              fontSize: "12px",
                              color: "#666",
                            }}
                          >
                            <svg
                              width="14"
                              height="14"
                              fill="none"
                              stroke="currentColor"
                              strokeWidth="2"
                              viewBox="0 0 24 24"
                              style={{ marginRight: "8px" }}
                            >
                              <circle cx="11" cy="11" r="8" />
                              <path d="m21 21-4.35-4.35" />
                            </svg>
                            Find Students
                          </div>
                            <div className="table-responsive" style={{ borderRadius: '3px' }}>
                            <table
                              className="table mb-0"
                              style={{
                                borderLeft: "1px solid #ddd",
                                borderRight: "1px solid #ddd",
                                minWidth: "600px",
                              }}
                            >
                            <thead>
                              <tr
                                style={{
                                  background: "#516275",
                                  color: "#fff",
                                  fontSize: "11px",
                                  letterSpacing: "0.5px",
                                }}
                              >
                                <th
                                  style={{
                                    fontWeight: "600",
                                    padding: "10px 15px",
                                    border: "none",
                                  }}
                                >
                                  LAST NAME ▾
                                </th>
                                <th
                                  style={{
                                    fontWeight: "600",
                                    padding: "10px 15px",
                                    border: "none",
                                  }}
                                >
                                  FIRST NAME ▾
                                </th>
                                <th
                                  style={{
                                    fontWeight: "600",
                                    padding: "10px 15px",
                                    border: "none",
                                  }}
                                >
                                  ASSESSMENT SCORE ▾
                                </th>
                                <th
                                  style={{
                                    fontWeight: "600",
                                    padding: "10px 15px",
                                    border: "none",
                                  }}
                                >
                                  STATUS ▾
                                </th>
                              </tr>
                            </thead>
                            <tbody>
                              {studentsByAssessment[a._id].length ? (
                                studentsByAssessment[a._id].map((s) => {
                                  const parts = s.name.split(" ");
                                  const firstName = parts[0];
                                  const lastName =
                                    parts.slice(1).join(" ") || "-";
                                  return (
                                    <tr
                                      key={s.name}
                                      style={{
                                        background: "white",
                                        borderBottom: "1px solid #ddd",
                                      }}
                                    >
                                      <td
                                        style={{
                                          padding: "12px 15px",
                                          fontSize: "13px",
                                          color: "#333",
                                        }}
                                      >
                                        {lastName}
                                      </td>
                                      <td
                                        style={{
                                          padding: "12px 15px",
                                          fontSize: "13px",
                                          color: "#333",
                                        }}
                                      >
                                        {firstName}
                                      </td>
                                      <td
                                        style={{
                                          padding: "12px 15px",
                                          fontSize: "13px",
                                          color: "#333",
                                        }}
                                      >
                                        {Number(s.score ?? 0).toFixed(2)}%
                                      </td>
                                      <td style={{ padding: "12px 15px" }}>
                                        {s.status === "At Risk" ? (
                                          <svg
                                            width="12"
                                            height="12"
                                            style={{ fill: "#d32f2f" }}
                                          >
                                            <path d="M0,0 L12,0 L6,10 Z" />
                                          </svg>
                                        ) : (
                                          <svg
                                            width="12"
                                            height="12"
                                            style={{ fill: "#388e3c" }}
                                          >
                                            <path d="M6,0 L12,10 L0,10 Z" />
                                          </svg>
                                        )}
                                      </td>
                                    </tr>
                                  );
                                })
                              ) : (
                                <tr
                                  style={{
                                    background: "white",
                                    borderBottom: "1px solid #ddd",
                                  }}
                                >
                                  <td
                                    colSpan={4}
                                    className="text-muted"
                                    style={{ padding: "15px" }}
                                  >
                                    No students found.
                                  </td>
                                </tr>
                              )}
                            </tbody>
                            </table>
                            </div>
                          <div
                            style={{
                              height: "15px",
                              background: "white",
                              borderLeft: "1px solid #ddd",
                              borderRight: "1px solid #ddd",
                              borderBottom: "1px solid #ddd",
                              marginBottom: "20px",
                            }}
                          />
                        </div>
                      </td>
                    </tr>
                  ) : null}
                </Fragment>
              ))
            ) : (
              <tr>
                <td
                  colSpan={6}
                  className="text-muted py-4 text-center"
                  style={{ background: "white" }}
                >
                  No assessments found.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  </div>
  );

  return (
    <Layout>
      {!isEditing && report ? (
        <>
          <div
            className="d-flex flex-column flex-md-row justify-content-between align-items-md-center mb-3 gap-3"
            style={{ borderBottom: "1px solid #ddd", paddingBottom: "12px" }}
          >
            <div>
              <div
                style={{
                  color: "#1a73c1",
                  fontSize: "11px",
                  textTransform: "uppercase",
                  fontWeight: 600,
                  letterSpacing: "0.5px",
                }}
              >
                <span onClick={onBack} style={{ cursor: "pointer" }}>
                  ADVANCED REPORTS
                </span>{" "}
                /
              </div>
              <div
                style={{
                  fontSize: "24px",
                  color: "#333",
                  fontWeight: 300,
                  display: "flex",
                  alignItems: "center",
                  gap: "8px",
                }}
              >
                Course
                <button
                  onClick={() => setIsEditing(true)}
                  style={{
                    border: "none",
                    background: "none",
                    cursor: "pointer",
                    color: "#1a73c1",
                    padding: 0,
                  }}
                >
                  <svg
                    width="14"
                    height="14"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                  >
                    <path d="M12 20h9M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z" />
                  </svg>
                </button>
              </div>
            </div>

            <div className="d-flex align-items-center gap-3">
              <button
                onClick={handleDelete}
                onMouseLeave={() => setIsConfirmingDelete(false)}
                style={{
                  border: isConfirmingDelete ? "1px solid #d32f2f" : "none",
                  background: isConfirmingDelete ? "#fff5f5" : "none",
                  fontSize: "11px",
                  fontWeight: 600,
                  color: "#d32f2f",
                  display: "flex",
                  alignItems: "center",
                  gap: "4px",
                  padding: "4px 8px",
                  borderRadius: "4px",
                }}
              >
                <svg
                  width="14"
                  height="14"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                >
                  <path d="M3 6h18M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />
                </svg>
                {isConfirmingDelete ? "CONFIRM DELETE?" : "DELETE"}
              </button>
              <button
                onClick={() => setIsEditing(true)}
                style={{
                  border: "none",
                  background: "none",
                  fontSize: "11px",
                  fontWeight: 600,
                  color: "#1a73c1",
                  display: "flex",
                  alignItems: "center",
                  gap: "4px",
                }}
              >
                <svg
                  width="14"
                  height="14"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                >
                  <circle cx="12" cy="12" r="3" />
                  <path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z" />
                </svg>
                EDIT & CREATE NEW
              </button>
              <button
                className="btn btn-sm"
                style={{
                  background: "#008e45",
                  color: "white",
                  fontSize: "11px",
                  fontWeight: 600,
                  border: "none",
                  padding: "6px 14px",
                  borderRadius: "3px",
                }}
                onClick={() => generateReport(false)}
              >
                RERUN REPORT
              </button>
            </div>
          </div>
          {renderReportBody()}
        </>
      ) : (
        <ReportFormShell
          title="Course Performance Report"
          reportName={reportName}
          onBack={onBack}
          onGenerate={() => generateReport(false)}
          onDelete={reportDbId ? handleDelete : undefined}
          isConfirmingDelete={isConfirmingDelete} // Pass this down if shell needs it
          isGenerating={isGenerating}
        >
          <div className="d-flex">
            <ReportFormLeft
              reportName={reportName}
              setReportName={setReportName}
              startDate={startDate}
              setStartDate={setStartDate}
              endDate={endDate}
              setEndDate={setEndDate}
              courses={courses}
              courseId={courseId}
              setCourseId={setCourseId}
            />
            <div className="col-divider" />
            <ReportFormRight
              sliders={SLIDERS}
              onValuesChange={({
                assessmentTypes: nextAssessmentTypes,
                sliderValues: nextSliderValues,
              }) => {
                setAssessmentTypes(nextAssessmentTypes || assessmentTypes);
                setSliderValues((prev) => ({
                  ...prev,
                  ...(nextSliderValues || {}),
                }));
              }}
            />
          </div>
          {error && <div className="alert alert-danger mt-3">{error}</div>}
          {report && renderReportBody()}
        </ReportFormShell>
      )}
    </Layout>
  );
}
